### ISSUE TITLE
Dynamic Job Vacancies

### ISSUE THREAD

**Issue by prachinav** [SE-Group-95/campus-job-review-system#1]
Create real-time updates for job postings without manual refresh.

**Comment by MayurG26** [comment]
Implemented a web scraper using BeautifulSoup to dynamically fetch all open job positions from the Campus Enterprises job portal, providing direct links to each job listing to ensure users have access to real-time job information. The job listings page automatically refreshes every hour, updating with the latest positions without requiring manual intervention.
