### ISSUE TITLE
Advanced Search Filters

### ISSUE THREAD

**Issue by prachinav** [SE-Group-95/campus-job-review-system#2]
- Adds filters like job type, salary range, and skills for more precise job searches.
- Develop a search system using Elasticsearch, with advanced filters like location and salary, and build a recommendation engine for personalized job suggestions.

**Comment by prachinav** [comment]
@22SiD is this PR merged? If so, can you you please update the issue and close it if done.

**Comment by MayurG26** [comment]
yes
