### ISSUE TITLE
Containerization for Scalable Deployment

### ISSUE THREAD

**Issue by prachinav** [SE-Group-95/campus-job-review-system#3]
- Containerize the application using Docker
- Integrating Docker Compose for multi-container environments
- Leverage Kubernetes for automated scaling and load balancing

**Comment by MayurG26** [comment]
Can you update the steps for deployment accordingly in  README.md and INSTALL.md?

**Comment by prachinav** [comment]
Merged https://github.com/SE-Group-95/campus-job-review-system/pull/12. Closing this issue
